version: '3'

services:
  nginx:
    image: cr.yandex/crper7r61g5617jljv9e/nginx:1.25.3-alpine3.18
    ports: 
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
    # depends_on:
    #   - mysql