version: '3.8'

services:
  nginx:
    image: cr.yandex/crper7r61g5617jljv9e/nginx:1.25.3-alpine3.18
    ports: 
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
    deploy:
      resources:
        reservations:
          # cpus: 0.25
          memory: 512M 
        limits:
          cpus: 0.50
          memory: 1G 
    # depends_on:
    #   - mysql