version: '3.8'

services:
  nginx:
    image: cr.yandex/crper7r61g5617jljv9e/nginx:${VERSION_IMAGE}
    ports: 
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
    deploy:
      resources:
        reservations:
          # cpus: 0.25
          memory: 512M 
        limits:
          cpus: 0.50
          memory: 1G 
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "--quiet", "http://localhost:5000/nginx_status"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 60s 
    restart: always
    # networks:
    #         - br_all
    # external_links:
    #   - localhost        
    # environment:
    #   - SCRAPE_URI=http://nginx:5000/nginx_status
    #   - NGINX_RETRIES=5
    #   - DATABASE_URL: "postgresql://itana-catalog:cCjE81IRFJ@rc1c-5ncryhijazm3o3o6.mdb.yandexcloud.net:6432/nrava"
    # external_links:
    #   - nginx_proxy:api.nrava.ru
    # env_file:
    #   - ./nrava_secrets.yaml  
    # depends_on:
    #   - mysql

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    container_name: nginx-exporter
    restart: always
    depends_on:
      - nginx
    environment:
      - SCRAPE_URI=http://nginx:5000/nginx_status
      - NGINX_RETRIES=5
    ports:
      - 9113:9113 
    # networks:
    #         - br_all   
# networks:
#     br_all:
#         driver: bridge
#     elasticsearch_net:
#         driver: bridge
#     neo4j_net:
#         driver: bridge