#GEOIP
load_module modules/ngx_http_geoip2_module.so;
#load_module modules/ngx_stream_geoip2_module.so;

user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    client_body_temp_path /tmp/client_body_temp;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp; 

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;
    
    # GEOIP
    
    # Whitelist-сети добавляются для исключения блокировки совсем 403 и для ограничения запросов 429
    geo $is_whitelisted {
        default 0;
        include /etc/nginx/whitelist.conf;
    }

    # Переменные для проверки Whitelist - если IP в списке то 1, если нет то 0
    map $is_whitelisted $skip_geoip_block { 1 "yes"; 0 "no"; }
    map $is_whitelisted $skip_rate_limit { 1 "yes"; 0 "no"; }

	# Объединённое условие блокировки 403 -  Страна не разрешена (no) И IP не в whitelist (no)-тогда $block_access=1(блокировать), в остальных - нет
    map "$allowed_country:$skip_geoip_block" $block_access {
        default 0;
        "no:no" 1;
    }
    
    # Объединённое условие для ограничения скорости 
	map "$allowed_country:$skip_rate_limit" $apply_rate_limit {
		default 1;       # по умолчанию применяем rate limit
		"yes:yes" 0;     # если страна разрешена и IP в whitelist - не лимитируем
		"yes:no" 0;      # страна разрешена, IP не в whitelist - не лимитируем 
		"no:yes" 0;      # страна не разрешена, но IP в whitelist - не лимитируем
		"no:no" 1;       # страна не разрешена и IP не в whitelist - лимитируем
	}
    
	# Путь к базе, присваиваем исо код, если не найдено в базе - РУ
	geoip2 /usr/share/geoip/GeoLite2-Country.mmdb {
		$geoip2_data_country_iso_code default=RU source=$remote_addr country iso_code;
	}

    # Создаётся новая переменная $allowed_country на основе значения переменной $geoip2_data_country_iso_code
	map $geoip2_data_country_iso_code $allowed_country {
		default no;
		~^(RU|US)$ yes;
		~^(DE|FR|UA)$ no;
		# RU yes;
        # US yes; # USA
		# NL yes; # Netherlands
		# DE yes; # Germany
		# FR yes; # France
		# UK yes; # United Kingdom of Great Britain and Northern Ireland
		# SE yes; # Sweden
		# UA yes; # Ukraine
		# CA yes; # Canada
		# BE yes; # Belgium
		# CH yes; # Switzerland
		# NO yes; # Norway
		# https://www.iso.org/obp/ui/#search
	}

    # Если $country_code пустой - ограничение не сработает.
    # Если $country_code установлен (например, "US" или "CN"), то лимит будет применяться для всех клиентов из этой страны.
	map $allowed_country $country_code {
		default $geoip2_data_country_iso_code;
		yes "";
	}

    # Новый ключ для rate limit с учётом whitelist и разрешённых стран
	map $apply_rate_limit $limit_key {
		1 $country_code;
		0 "";
	}

	# Ограничение request_rate для всех стран, кроме разрешенных и не из whitelist. rate=Xr/m на каждую страну.
	limit_req_zone $limit_key zone=limit_req_rate:20m rate=40r/m;

    # geoip2 /usr/share/geoip/GeoLite2-City.mmdb {
    #     $geoip2_data_city_name default=Москва city names ru;
    # }

	# /GEOIP

    include /etc/nginx/conf.d/*.conf;
}
